stages:
  - test

cargo fmt:
  stage: test
  image: rust:latest
  script:
    - cargo fmt -- --check
  artifacts:
    paths:
      - target/
  except:
    - deploy

cargo clippy:
  stage: test
  image: rust:latest
  script:
    - cargo clippy -- -D warnings
  except:
    - deploy
