stages:
  - test

cargo fmt:
  stage: test
  image: rust:latest
  script:
    - cargo fmt -- --check
  artifacts:
    paths:
      - target/
  only:
    - merge_requests
    - master

cargo clippy:
  stage: test
  image: rust:latest
  script:
    - cargo clippy -- -D warnings
  only:
    - merge_requests
    - master
