stages:
  - build

rust:
  image: rust:nightly
  stage: build
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings