[package]
name = "drone-goes-brrr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tudelft-quadrupel = {version="1"}
micromath = "2.0.0"
cordic = "0.1.5"
postcard = "1.0.4"
serde = {version="1.0.152", default-features = false, features = ["alloc"]}
protocol = {path = "../protocol"}